### ISSUE TITLE
Ошибка в кластер-клиенте при попытке вычитать тело HEAD запроса

### ISSUE THREAD

**Issue by spaceorc** [vostok/clusterclient.transport.systemnethttp#1]
```
2019-08-15 15:16:22,828 ERROR [XcomApiClient] Failed to read response body.
System.IO.EndOfStreamException: Response stream ended prematurely. Read only 0 byte(s), but Content-Length header specified 6.
   at Vostok.Clusterclient.Transport.SystemNetHttp.BodyReading.BodyReader.ReadWithKnownLengthAsync(Stream stream, Int32 contentLength, CancellationToken cancellationToken)
   at Vostok.Clusterclient.Transport.SystemNetHttp.BodyReading.BodyReader.ReadAsync(HttpResponseMessage message, CancellationToken cancellationToken)
2019-08-15 15:16:22,831 ERROR [XcomApiClient] Failed with status 'ReplicasExhausted'. Response code = 451 ('ReceiveFailure'). Time = .

```

**Comment by spaceorc** [comment]
Content-Length != 0, это требует RFC2616:

The Content-Length entity-header field indicates the size of the entity-body, in decimal number of OCTETs, sent to the recipient or, in the case of the HEAD method, the size of the entity-body that would have been sent had the request been a GET.

**Comment by spaceorc** [comment]
https://github.com/vostok/clusterclient.transport.sockets/pull/2

**Comment by iloktionov** [comment]
Fixed in all transport implementations.
